version: 2
build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    install:
      - pip install --upgrade pip
      - pip install --group doc .
sphinx:
  configuration: doc/conf.py
formats: all
