dist: bionic
language: python
matrix:
  include:
  - python: "3.8"
  - python: "3.7"
  - python: "3.6"
  - python: "3.5"
  - python: "nightly"
  - python: "pypy3"
  - os: osx
    language: generic
  - name: build docs and check for broken links
    install:
      - python3 -m pip install -r doc/requirements.txt
    script:
      - python3 setup.py build_sphinx -b linkcheck -W
addons:
  apt:
    packages:
      - pandoc
      - libportaudio2
install:
  - python3 -m pip install .
script:
  - cd /tmp
  - python3 -m sounddevice
  - python3 -c "import sounddevice as sd; print(sd._libname)"
  - python3 -c "import sounddevice as sd; print(sd.get_portaudio_version())"
notifications:
  email: false
